### ISSUE TITLE
VAST Plugin displays countdown time after the ad is played with wrong time - occasionally 

### ISSUE THREAD

**Issue by adamtspin** [kaltura/kdp#7]
We're seeing issues where the VAST Plugin is displaying the countdown timer after the ad plays.  When the time hangs, it then switches to the time of the content video.  Unfortunately, this is an intermittent issue.

/kdp/tree/master/plugins/vastPlugin

**Comment by MichalRadwantzor** [comment]
Hi,
this usually means that one of your vast prerolls failed to play. Please check your vast config.

**Comment by adamtspin** [comment]
Thanks for commenting.  We are currently using DFP tags in our config.  And, the issue happens AFTER the preroll plays.

**Comment by MichalRadwantzor** [comment]
The countdown label is bound to sequenceProxy.isAdLoaded attribute, meaning, it will show only if this value is true. You can look at vastPlugin code and see when is this attribute being set and why isn't it being set back to false after the ad has ended. My guess is that you have multiple ads in the preroll break and one of the ads fails to play to isAdLoaded value remains true.
If you're having problems finding the root cause you can send me a link and I will try to take a look.
